### ISSUE TITLE
Problem with jupyterhub

### ISSUE THREAD

**Issue by koencolpaert** [keberwein/Data_Science_Workbench#2]
I'm using the 16.04 script but it fails at:
`/opt/anaconda3/bin/./pip install jupyterhub
bash: /opt/anaconda3/bin/./pip: No such file or directory
`

**Comment by keberwein** [comment]
The root of the problem was Anaconda. The script was installing an old version. Fixed.

https://github.com/keberwein/Data_Science_Workbench/commit/f5f8d954c876a8ccbc5321166ba4937ff50a295e
